Fix/resposive
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #100
Opened 2023-01-25 16:08 UTC by SkeidoK

2023-01-25 16:14 UTC, codelande approved these changes

2023-01-25 16:14 UTC, codelande commented on apps/frontend/web/src/App.tsx
> +        <Route path="/game/overview" element={<Overview />} />
je pense qu'il faut laisser le protected

2023-01-25 16:17 UTC, SkeidoK commented on apps/frontend/web/src/App.tsx
> +        <Route path="/game/overview" element={<Overview />} />
Bien vu

2023-01-25 16:23 UTC, codelande submitted a review, later dismissed

2023-01-25 18:17 UTC, YDrogen requested changes

2023-01-25 18:17 UTC, YDrogen commented on apps/frontend/web/src/pages/Assistance.tsx
> +                <FormErrorMessage>Title is required.</FormErrorMessage>
`{""}`

2023-01-25 18:17 UTC, YDrogen commented on apps/frontend/web/src/pages/About.tsx
> +          <Heading mt="20">{'La team'}</Heading>
Du français ?

2023-01-25 18:17 UTC, YDrogen commented on apps/frontend/web/src/pages/About.tsx
> +              {'Icons Flaticon : Référence des icônes sur ce lien'}
Encore ?

2023-01-26 16:05 UTC, codelande approved these changes

2023-01-26 16:18 UTC, YDrogen approved these changes

2023-01-26 16:18 UTC, merged