Fix/front account settings
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #104
Opened 2023-01-30 10:18 UTC by codelande

2023-01-30 10:26 UTC, YDrogen requested changes

2023-01-30 10:26 UTC, YDrogen commented on apps/frontend/web/src/App.tsx
> +          setIsLoadingUser(false);
ceci doit être dans le else

2023-01-30 10:26 UTC, YDrogen commented on apps/frontend/web/src/components/Protected.tsx
> +    return <>ca charge</>;
return `null` ça suffit :D

2023-01-30 10:26 UTC, YDrogen commented on apps/frontend/web/src/contexts/AuthContext.tsx
Par ici, il faut un `useEffect` qui set `isLoading` à `false` si `user`

2023-01-31 08:37 UTC, ngroult submitted a review, later dismissed

2023-01-31 10:49 UTC, paul-chatelain-fernandes requested changes

2023-01-31 10:49 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/UserImageFiller.tsx
> +  setFormData: any;
`any` ?

2023-01-31 10:49 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/AccountSettings.tsx
> +  const [formData, setFormData] = useState<{ [key: string]: any }>({});
`any` aussi ?

2023-01-31 13:52 UTC, codelande commented on apps/frontend/web/src/pages/AccountSettings.tsx
> +  const [formData, setFormData] = useState<{ [key: string]: any }>({});
celui la c normal ;)

2023-02-01 10:54 UTC, paul-chatelain-fernandes approved these changes

2023-02-01 11:00 UTC, YDrogen requested changes

2023-02-01 11:09 UTC, codelande commented on apps/frontend/web/src/App.tsx
> +    setIsLoadingUser(false);
je sais pas

2023-02-01 11:11 UTC, codelande commented on apps/frontend/web/src/App.tsx
> +    setIsLoadingUser(false);
:face_in_clouds:

2023-02-01 11:25 UTC, paul-chatelain-fernandes approved these changes

2023-02-01 11:31 UTC, YDrogen approved these changes

2023-02-01 11:31 UTC, merged