feat:can now delete game or user
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #108
Opened 2023-01-30 15:42 UTC by codelande

2023-02-01 10:55 UTC, paul-chatelain-fernandes approved these changes

2023-02-01 11:03 UTC, YDrogen requested changes

2023-02-01 11:03 UTC, YDrogen commented on apps/frontend/web/src/components/popups/SlideUpModal.tsx
> +import { useActionData } from 'react-router-dom';
jamais utilisé ?

2023-02-01 11:03 UTC, YDrogen commented on apps/frontend/web/src/pages/AccountSettings.tsx
> +  };
Gestion d'erreur ? Message de confirmation ? Que se passe-t-il ??

2023-02-01 11:03 UTC, YDrogen commented on apps/frontend/web/src/pages/GameSettings.tsx
> +  };
idem ?

2023-02-01 15:43 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2023-02-01 15:50 UTC, YDrogen requested changes

2023-02-01 15:50 UTC, YDrogen commented on apps/frontend/web/src/pages/AccountSettings.tsx
> +      });
non
il se passe quoi quand tu cliques ?

2023-02-01 15:50 UTC, YDrogen commented on apps/frontend/web/src/pages/GameSettings.tsx
> +      });
du coup, non plus

2023-02-02 10:24 UTC, paul-chatelain-fernandes approved these changes

2023-02-02 10:44 UTC, YDrogen approved these changes

2023-02-02 10:44 UTC, merged