Feature/get images from db for forms
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #113
Opened 2023-02-01 09:07 UTC by codelande

2023-02-01 11:27 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2023-02-01 15:44 UTC, paul-chatelain-fernandes approved these changes

2023-02-01 15:52 UTC, YDrogen requested changes

2023-02-01 15:52 UTC, YDrogen commented on apps/frontend/web/src/components/GameImageFiller.tsx
> +    imagesGet();
Ça veut rien dire `imagesGet`

2023-02-01 15:52 UTC, YDrogen commented on apps/frontend/web/src/components/UserImageFiller.tsx
> +    imagesGet();
idem

2023-02-02 08:32 UTC, paul-chatelain-fernandes approved these changes

2023-02-02 10:25 UTC, paul-chatelain-fernandes approved these changes

2023-02-02 15:31 UTC, merged