feat: resolve issue with setIsLoadingUser
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #120
Opened 2023-02-02 09:52 UTC by paul-chatelain-fernandes

2023-02-02 10:23 UTC, codelande submitted a review, later dismissed

2023-02-02 15:36 UTC, YDrogen requested changes

2023-02-02 15:36 UTC, YDrogen commented on apps/frontend/web/src/components/Navbar.tsx
> +        navigate('/');
il faut reset le user du context

2023-02-03 09:11 UTC, codelande approved these changes

2023-02-03 10:50 UTC, YDrogen approved these changes

2023-02-03 10:50 UTC, merged