feat(frontend/web): remove all console.log
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #123
Opened 2023-02-02 10:39 UTC by paul-chatelain-fernandes

2023-02-02 10:48 UTC, codelande approved these changes

2023-02-02 10:48 UTC, Ysedda requested changes

2023-02-02 10:48 UTC, Ysedda commented on apps/frontend/web/src/components/CharacterCard.tsx
> +      } catch (err) {}
```suggestion
      } catch {}
```

2023-02-02 10:48 UTC, Ysedda commented on apps/frontend/web/src/components/CharacterCard.tsx
> +      } catch (err) {}
```suggestion
      } catch {}
```

2023-02-02 10:48 UTC, Ysedda commented on apps/frontend/web/src/components/EventCard.tsx
> +      } catch (err) {}
```suggestion
      } catch {}
```

2023-02-02 10:48 UTC, Ysedda commented on apps/frontend/web/src/pages/Room.tsx
> +      } catch (err) {}
```suggestion
      } catch {}
```

2023-02-02 10:48 UTC, Ysedda commented on apps/frontend/web/src/pages/Room.tsx
> +      } catch (err) {}
```suggestion
      } catch {}
```

2023-02-02 10:48 UTC, Ysedda commented on apps/frontend/web/src/pages/Room.tsx
> +      } catch (err) {}
```suggestion
      } catch {}
```

2023-02-02 15:39 UTC, YDrogen requested changes
oui

2023-02-03 09:12 UTC, codelande approved these changes

2023-02-03 10:50 UTC, YDrogen approved these changes

2023-02-03 10:50 UTC, merged