feat(frontend/web): handle press enter to submit form
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #125
Opened 2023-02-02 11:26 UTC by paul-chatelain-fernandes

2023-02-02 11:27 UTC, codelande approved these changes

2023-02-03 09:13 UTC, codelande submitted a review, later dismissed

2023-02-03 10:52 UTC, YDrogen requested changes

2023-02-03 11:39 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/Login.tsx
> +              color="var(--chakra-colors-red-500)"
Pour feur Sylvain, pour feur

2023-02-03 13:05 UTC, SkeidoK approved these changes

2023-02-03 15:09 UTC, YDrogen approved these changes

2023-02-03 15:09 UTC, merged