feat: add bonus in procedure
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #126
Opened 2023-02-03 11:39 UTC by SkeidoK

2023-02-03 11:41 UTC, paul-chatelain-fernandes approved these changes

2023-02-03 15:10 UTC, YDrogen requested changes

2023-02-03 15:10 UTC, YDrogen commented on deployment/sql/02.sql
> +    DECLARE isBonusType VARCHAR(255);
utiles ?

2023-02-03 15:10 UTC, YDrogen commented on deployment/sql/02.sql
> +
Non !

2023-02-03 15:42 UTC, SkeidoK commented on deployment/sql/02.sql
> +    DECLARE isBonusType VARCHAR(255);
Oui

2023-02-03 15:46 UTC, SkeidoK commented on deployment/sql/02.sql
> +    DECLARE isBonusType VARCHAR(255);
Enfaite non

2023-02-03 16:05 UTC, codelande approved these changes

2023-02-03 17:25 UTC, YDrogen approved these changes

2023-02-04 15:06 UTC, paul-chatelain-fernandes approved these changes

2023-02-06 08:25 UTC, YDrogen approved these changes

2023-02-06 08:25 UTC, merged