feat: refactor forge service
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #131
Opened 2023-02-06 13:48 UTC by paul-chatelain-fernandes

2023-02-07 15:19 UTC, codelande approved these changes

2023-02-07 15:24 UTC, codelande requested changes

2023-02-07 15:24 UTC, codelande commented on apps/frontend/web/src/components/UserPasswordFiller.tsx
> +        onChange={() => {}}
pourquoi cette fonction vide ?

2023-02-07 15:24 UTC, codelande commented on apps/frontend/web/src/pages/GameSettings.tsx
> +        console.log(response);
log paul...

2023-02-08 13:30 UTC, codelande approved these changes

2023-02-08 14:30 UTC, codelande approved these changes

2023-02-08 14:44 UTC, YDrogen requested changes
image

2023-02-08 14:44 UTC, YDrogen commented on apps/frontend/web/src/pages/NewGame.tsx
> +      image: { id: parseInt(companyImage, 10) },
???
parseInt de `man1` ?

2023-02-08 14:44 UTC, YDrogen commented on apps/frontend/web/src/pages/NewGame.tsx
> +      const response = await fetch('/api/games/', {
```suggestion
      const response = await fetch('/api/games', {
```

2023-02-09 09:40 UTC, codelande submitted a review, later dismissed

2023-02-09 13:04 UTC, codelande approved these changes

2023-02-09 13:29 UTC, YDrogen requested changes

2023-02-09 13:29 UTC, YDrogen commented on apps/frontend/web/src/pages/NewGame.tsx
> +  const [selectedImageId, setSelectedImageId] = useState(21);
image en dur ?

2023-02-09 15:27 UTC, codelande approved these changes

2023-02-09 15:33 UTC, YDrogen approved these changes

2023-02-09 15:34 UTC, merged