feat: add column point remove ceo name
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #132
Opened 2023-02-06 15:31 UTC by SkeidoK

2023-02-06 18:58 UTC, paul-chatelain-fernandes requested changes

2023-02-06 18:58 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +                        {'$'} {gameResource[0].quantity}
Faudrait tout mettre dans une seule template string pour faire plus propre (s'il n'y a pas de problème avec les `$` collés
``{`$${gameResource[0].quantiy}`}``

2023-02-07 10:30 UTC, SkeidoK commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +                        {'$'} {gameResource[0].quantity}
Ok d'acc

2023-02-07 11:18 UTC, codelande submitted a review, later dismissed

2023-02-07 11:32 UTC, YDrogen requested changes

2023-02-07 11:32 UTC, YDrogen commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +    fetch('api/game-resources', { method: 'GET' })
Il manque un `/`

2023-02-07 11:32 UTC, YDrogen commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +        setGameResource(data1);
`data` ?

2023-02-07 11:32 UTC, YDrogen commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +                      <Td>{`$ ${gameResource[0].quantity}`}</Td>
```suggestion
                      <Td>{`$${gameResource[0].quantity}`}</Td>
```

2023-02-07 13:18 UTC, SkeidoK commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +        setGameResource(data1);
J'ai mis `response` pour ne pas avoir data deux fois alors que ce n'ai pas les même infos

2023-02-07 13:18 UTC, SkeidoK commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +    fetch('api/game-resources', { method: 'GET' })
Bien vu

2023-02-07 13:28 UTC, codelande approved these changes

2023-02-07 13:33 UTC, YDrogen approved these changes

2023-02-07 13:34 UTC, paul-chatelain-fernandes approved these changes

2023-02-07 13:34 UTC, merged