Feature/add characters
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #141
Opened 2023-02-09 15:43 UTC by ngroult

2023-02-09 16:07 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/CharacterCard.tsx
> +    } catch (e) {}
Faut juste enlever `(e)`, mais tu peux laisser les accolades

2023-02-09 16:19 UTC, paul-chatelain-fernandes approved these changes

2023-02-09 16:46 UTC, YDrogen requested changes

2023-02-09 16:46 UTC, YDrogen commented on apps/backend/api/src/app/game-characters/game-characters.service.ts
> +      .leftJoinAndSelect('gameResources.resource', 'resource')
Tout est optionnel ? Si c'est obligatoire, tu peux mettre `inner`

2023-02-09 16:46 UTC, YDrogen commented on apps/backend/api/src/app/game-characters/game-characters.service.ts
> +    if (countSizeGameRoom <= gameChar.character.room.gameRooms[0].totalSize) {
quelques sauts de ligne pour la lisibilité 👀

2023-02-09 16:46 UTC, YDrogen commented on apps/backend/api/src/app/game-characters/game-characters.service.ts
> +    } else {
sauts de ligne aussi c:

2023-02-09 16:46 UTC, YDrogen commented on apps/frontend/web/src/components/ResourcesBar.tsx
> +        countSizeCharacters();
quand tu appelle `countSizeCharacters`, le state n'est peut-être pas encore à jour

2023-02-09 16:46 UTC, YDrogen commented on apps/frontend/web/src/components/ResourcesBar.tsx
> +          if (gameCharacters[i].quantity != 0) {
`!==`

2023-02-10 08:23 UTC, ngroult commented on apps/backend/api/src/app/game-characters/game-characters.service.ts
> +    if (countSizeGameRoom <= gameChar.character.room.gameRooms[0].totalSize) {
fait

2023-02-10 08:23 UTC, ngroult commented on apps/backend/api/src/app/game-characters/game-characters.service.ts
> +      .leftJoinAndSelect('gameResources.resource', 'resource')
fait

2023-02-10 08:24 UTC, ngroult commented on apps/backend/api/src/app/game-characters/game-characters.service.ts
> +    } else {
fait

2023-02-10 08:32 UTC, ngroult commented on apps/frontend/web/src/components/ResourcesBar.tsx
> +          if (gameCharacters[i].quantity != 0) {
idem

2023-02-10 08:32 UTC, ngroult commented on apps/frontend/web/src/components/ResourcesBar.tsx
> +        countSizeCharacters();
en fait je viens de supprimer ça car ce calcul est maintenant fait côté backend dans la méthode Patch AddGameCharacters du service GameCharacters

2023-02-10 08:35 UTC, ngroult commented on apps/backend/api/src/app/game-characters/game-characters.service.ts
> +      .leftJoinAndSelect('gameResources.resource', 'resource')
Changé en inner

2023-02-10 08:44 UTC, SkeidoK submitted a review, later dismissed

2023-02-10 08:45 UTC, codelande approved these changes

2023-02-10 08:56 UTC, YDrogen requested changes

2023-02-10 08:56 UTC, YDrogen commented on apps/frontend/web/src/components/CharacterCard.tsx
> +          description: `Congratulations, you hire : ${gameCharacter.character.name}!`,
```suggestion
          description: `Congratulations, you hired: ${gameCharacter.character.name}!`,
```

2023-02-10 08:56 UTC, YDrogen commented on apps/frontend/web/src/components/CharacterCard.tsx
> +          description: `You don't have any resources or space in your ${gameRoom.room.name} !`,
```suggestion
          description: `You don't have any resources or space in your ${gameRoom.room.name}!`,
```

2023-02-10 08:58 UTC, ngroult commented on apps/frontend/web/src/components/CharacterCard.tsx
> +          description: `Congratulations, you hire : ${gameCharacter.character.name}!`,
fait, merci je suis nulle en anglais

2023-02-10 08:58 UTC, ngroult commented on apps/frontend/web/src/components/CharacterCard.tsx
> +          description: `You don't have any resources or space in your ${gameRoom.room.name} !`,
fait

2023-02-10 09:00 UTC, SkeidoK submitted a review, later dismissed

2023-02-10 09:06 UTC, YDrogen requested changes

2023-02-10 09:06 UTC, YDrogen commented on apps/frontend/web/src/components/CharacterCard.tsx
> +          description: `Congratulations, you hired : ${gameCharacter.character.name}!`,
```suggestion
          description: `Congratulations, you hired: ${gameCharacter.character.name}!`,
```
attention l'espace :eyes:

2023-02-10 09:07 UTC, codelande approved these changes

2023-02-10 09:08 UTC, YDrogen approved these changes

2023-02-10 09:08 UTC, merged