feat(frontend/web): add image of mayor, restylize the front
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #155
Opened 2023-02-14 13:20 UTC by paul-chatelain-fernandes

2023-02-14 13:48 UTC, codelande requested changes

2023-02-14 13:48 UTC, codelande commented on apps/frontend/web/src/pages/Overview.tsx
> +        pt="80px"
je pense que le px/pt casse tout en resposive :(

2023-02-14 14:36 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/Overview.tsx
> +        pt="80px"
Tqt

2023-02-14 15:25 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/Overview.tsx
> +        pt="80px"
Ca va bien se passer

2023-02-14 15:31 UTC, codelande commented on apps/frontend/web/src/pages/Overview.tsx
> +        pt="80px"
ba non

2023-02-14 16:00 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/Overview.tsx
> +        pt="80px"
Envoie un screen stp pour me prouver le contraire

2023-02-15 08:31 UTC, codelande approved these changes

2023-02-15 11:01 UTC, YDrogen approved these changes

2023-02-15 11:01 UTC, merged