feat: add command docker compose
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #160
Opened 2023-02-14 16:24 UTC by codelande

2023-02-14 16:24 UTC, codelande commented
J'ai changer le docker compose dans le vps et delete le dossier db dans le dossier prod

2023-02-15 08:20 UTC, codelande commented
J'ai changer le docker compose dans le vps et delete le dossier db dans le dossier prod

2023-02-15 11:28 UTC, SkeidoK approved these changes

2023-02-15 13:25 UTC, YDrogen requested changes
La migration se fera dans la branche release donc il faut la retirer d'ici

2023-02-15 13:31 UTC, codelande commented
ca marche :+1:

2023-02-16 09:02 UTC, SkeidoK approved these changes

2023-02-16 09:10 UTC, YDrogen approved these changes

2023-02-16 09:10 UTC, merged