Release/0.1.0
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #165
Opened 2023-02-16 13:22 UTC by SkeidoK

2023-02-16 15:48 UTC, SkeidoK commented on apps/backend/api/src/config/migration.config.ts
> +  migrations: [__dirname + '/../migrations/*.ts'],
A revoir car ca ne marche pas, peut etre le scrypt ou ici jsp

2023-02-16 15:48 UTC, SkeidoK commented on apps/frontend/mobile/.env.sample
> +PORT=3333
pas 3333 dans le sample

2023-02-16 15:48 UTC, SkeidoK commented on apps/frontend/mobile/src/App.tsx
> +        console.warn(e);
a enlever ca ne sert a rien

2023-02-16 15:48 UTC, SkeidoK commented on apps/frontend/mobile/src/screens/OverviewScreen.tsx
> +      <Text>Overview</Text>
texte entre {' '}

2023-02-16 15:48 UTC, SkeidoK commented on apps/frontend/mobile/src/screens/RegisterScreen.tsx
> +  return <Text>Register</Text>;
texte entre {' '}

2023-02-16 15:48 UTC, SkeidoK commented on apps/frontend/web/src/App.tsx
> +        <Route path="/leaderboard" element={<Leaderboard />} />
je pense que la route leaderboard doit etre protecetd car si on essaye d'y acceder sans etre proteger il y aura un bug au momebt de  chercher le user actuel

2023-02-16 15:48 UTC, SkeidoK commented on libs/typings/src/interfaces/index.ts
> -export * from "./SomeInterface";
reelement utile ?

2023-02-16 16:05 UTC, MGliem commented on apps/backend/api/src/app/game-resources/game-resources.controller.ts
> +
Si c'est le cas, tu peux le mettre sur le controller directement au lieu de le mettre sur chaque méthode.
Néanmoins, il est possible que ca soit des routes et des méthodes créées auto par nest qui ne font rien. Dans ce cas là, il faut les supprimer

2023-02-16 16:07 UTC, MGliem commented on apps/backend/api/src/app/games/dto/create-game.dto.ts
> +    message: 'The CEO name must be between 3 and 30 characters length',
Effectivement, bien vu, ne pas mettre de length minimum

2023-02-16 16:07 UTC, MGliem commented on apps/backend/api/src/app/rooms/rooms.service.ts
> +    return this.roomsRepository.find({
je dirais même findOneBy (si pas de relations)

2023-02-16 16:08 UTC, MGliem commented on apps/backend/api/src/app/users/dto/create-user.dto.ts
> +  @Length(3, 30, {
comme sur le create game en effet

2023-02-16 16:08 UTC, MGliem commented on apps/backend/api/src/app/users/dto/register-user.dto.ts
> +  @Length(3, 30, {
idem

2023-02-16 16:10 UTC, MGliem commented on apps/backend/api/src/config/migration.config.ts
> +  migrations: [__dirname + '/../migrations/*.ts'],
En effet, sur le VPS, nest est build.
Par conséquent, une fois build, les fichiers sont des .js, il faut donc mettre ici:
migrations: [__dirname + '/../migrations/*.{ts,js}'],

2023-02-16 16:11 UTC, MGliem commented on apps/frontend/mobile/.env.sample
> +PORT=3333
Pas trop genant tant qu'on comprend que c'est le port de nest

2023-02-16 16:11 UTC, MGliem commented on apps/frontend/mobile/src/App.tsx
> +        console.warn(e);
en effet, les console.*** à ne pas garder

2023-02-16 16:12 UTC, MGliem commented on apps/frontend/mobile/src/screens/OverviewScreen.tsx
> +      <Text>Overview</Text>
:scream:

2023-02-16 16:13 UTC, MGliem commented on libs/typings/src/interfaces/index.ts
> -export * from "./SomeInterface";
Vous pouvez l'enlever mais faut penser que c'est peut être utilisé ailleurs et par conséquent l'enlever à cet endroit là

2023-02-16 16:14 UTC, codelande commented on apps/backend/api/src/app/game-resources/game-resources.controller.ts
> +
bien vu, j'ai effectivment vu la possibilité directement sur le controller

2023-02-16 16:15 UTC, codelande commented on apps/backend/api/src/app/games/dto/create-game.dto.ts
> +    message: 'The CEO name must be between 3 and 30 characters length',
:+1:

2023-02-16 16:15 UTC, codelande commented on apps/backend/api/src/app/rooms/rooms.service.ts
> +    return this.roomsRepository.find({
:+1:

2023-02-16 16:15 UTC, codelande commented on apps/backend/api/src/config/migration.config.ts
> +  migrations: [__dirname + '/../migrations/*.ts'],
merci pour l'explication :smile:

2023-02-16 16:17 UTC, codelande commented on libs/typings/src/interfaces/index.ts
> -export * from "./SomeInterface";
SomeInterface n'est il pas juste un exemple d'interface autogénérée ?

2023-02-16 16:51 UTC, YDrogen commented on libs/typings/src/interfaces/index.ts
> -export * from "./SomeInterface";
oui

2023-02-16 16:51 UTC, YDrogen commented on libs/typings/src/types/index.ts
> +export * from './DeepPartial';
?

2023-02-16 21:48 UTC, SkeidoK commented on apps/backend/api/src/config/migration.config.ts
> +  migrations: [__dirname + '/../migrations/*.ts'],
Merci pour l'info Max, je le fait demain en arrivant

2023-02-17 08:32 UTC, YDrogen commented on apps/backend/api/src/app/game-resources/game-resources.controller.ts
> +
oui

2023-02-17 08:32 UTC, YDrogen commented on apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
> +
ou sur le controller entier du coup

2023-02-17 08:33 UTC, YDrogen commented on apps/backend/api/src/app/games/dto/create-game.dto.ts
> +    message: 'The CEO name must be between 3 and 30 characters length',
oui

2023-02-17 08:33 UTC, YDrogen commented on apps/backend/api/src/app/rooms/rooms.service.ts
> +    return this.roomsRepository.find({
ça fonctionne comme ça et c'est pas un changement super important

2023-02-17 08:34 UTC, YDrogen commented on apps/backend/api/src/app/rooms/rooms.service.ts
> +    return this.roomsRepository.find({
de meme

2023-02-17 08:36 UTC, YDrogen commented on apps/frontend/mobile/src/screens/OverviewScreen.tsx
> +      <Text>Overview</Text>
oui

2023-02-17 08:36 UTC, YDrogen commented on apps/frontend/mobile/src/screens/RegisterScreen.tsx
> +  return <Text>Register</Text>;
oui

2023-02-17 08:38 UTC, SkeidoK commented on libs/typings/src/interfaces/index.ts
> -export * from "./SomeInterface";
Fait

2023-02-17 08:38 UTC, SkeidoK commented on libs/typings/src/types/index.ts
> +export * from './DeepPartial';
Fait

2023-02-17 08:38 UTC, SkeidoK commented on apps/frontend/web/src/App.tsx
> +        <Route path="/leaderboard" element={<Leaderboard />} />
Fait

2023-02-17 08:38 UTC, SkeidoK commented on apps/frontend/mobile/src/screens/RegisterScreen.tsx
> +  return <Text>Register</Text>;
Fait

2023-02-17 08:38 UTC, SkeidoK commented on apps/frontend/mobile/src/screens/OverviewScreen.tsx
> +      <Text>Overview</Text>
Fait

2023-02-17 08:39 UTC, SkeidoK commented on apps/frontend/mobile/src/App.tsx
> +        console.warn(e);
Fait

2023-02-17 08:40 UTC, SkeidoK commented on apps/frontend/mobile/.env.sample
> +PORT=3333
On laisse le 3333 (vu avec le formateur)

2023-02-17 08:40 UTC, SkeidoK commented on apps/backend/api/src/config/migration.config.ts
> +  migrations: [__dirname + '/../migrations/*.ts'],
Fait

2023-02-17 08:40 UTC, SkeidoK commented on apps/backend/api/src/app/users/dto/register-user.dto.ts
> +  @Length(3, 30, {
Fait

2023-02-17 08:40 UTC, SkeidoK commented on apps/backend/api/src/app/users/dto/create-user.dto.ts
> +  @Length(3, 30, {
Fait

2023-02-17 08:40 UTC, SkeidoK commented on apps/backend/api/src/app/games/dto/create-game.dto.ts
> +    message: 'The CEO name must be between 3 and 30 characters length',
Fait

2023-02-17 08:41 UTC, YDrogen commented on apps/backend/api/src/app/bonus-malus/bonus-malus.controller.ts
> +@Controller('bonus-malus')
Guard

2023-02-17 08:42 UTC, YDrogen commented on apps/backend/api/src/app/characters/character.controller.ts
> +@Controller('characters')
Guard

2023-02-17 08:43 UTC, YDrogen commented on apps/backend/api/src/app/events/dto/create-event.dto.ts
> +  name: string;
?

2023-02-17 08:43 UTC, YDrogen commented on apps/backend/api/src/app/events/events.controller.ts
> +@Controller('events')
Guard

2023-02-17 08:44 UTC, YDrogen commented on apps/backend/api/src/app/forge/forge.controller.ts
> +}
Ne pas mettre ça en prod

2023-02-17 08:53 UTC, YDrogen commented on apps/backend/api/src/app/game-events/game-events.controller.ts
> +@Controller('game-events')
Guard

2023-02-17 08:53 UTC, SkeidoK commented on apps/backend/api/src/app/game-resources/game-resources.controller.ts
> +
Fait

2023-02-17 08:53 UTC, SkeidoK commented on apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
> +
Fait

2023-02-17 08:53 UTC, YDrogen commented on apps/backend/api/src/app/game-resources/game-resources.controller.ts
> +@Controller('game-resources')
Guard

2023-02-17 08:56 UTC, YDrogen commented on apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
> +@Controller('game-rooms')
Guard

2023-02-17 08:56 UTC, SkeidoK commented on apps/backend/api/src/app/bonus-malus/bonus-malus.controller.ts
> +@Controller('bonus-malus')
Fait

2023-02-17 08:58 UTC, YDrogen commented on apps/backend/api/src/app/games/dto/create-game.dto.ts
> +  image: IdDto;
Attention, l'erreur de IdDto sera "Invalid user"

2023-02-17 08:59 UTC, YDrogen commented on apps/backend/api/src/app/games/games.controller.ts
> +@Controller('games')
Guard

2023-02-17 08:59 UTC, SkeidoK commented on apps/backend/api/src/app/characters/character.controller.ts
> +@Controller('characters')
Fait

2023-02-17 09:01 UTC, SkeidoK commented on apps/backend/api/src/app/events/dto/create-event.dto.ts
> +  name: string;
Fait

2023-02-17 09:01 UTC, SkeidoK commented on apps/backend/api/src/app/events/events.controller.ts
> +@Controller('events')
Fait

2023-02-17 09:03 UTC, SkeidoK commented on apps/backend/api/src/app/forge/forge.controller.ts
> +}
Commenter dans le app.module

2023-02-17 09:04 UTC, SkeidoK commented on apps/backend/api/src/app/game-events/game-events.controller.ts
> +@Controller('game-events')
Fait

2023-02-17 09:04 UTC, SkeidoK commented on apps/backend/api/src/app/game-resources/game-resources.controller.ts
> +@Controller('game-resources')
Fait

2023-02-17 09:04 UTC, SkeidoK commented on apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
> +@Controller('game-rooms')
Fait

2023-02-17 09:07 UTC, ngroult requested changes

2023-02-17 09:07 UTC, ngroult commented on apps/backend/api/src/app/games/games.service.ts
> +    return await this.gamesRepository.save(createGameDto);
Si je ne dis pas de bétises il ne faut pas qu'on mette de return await
```suggestion
    return this.gamesRepository.save(createGameDto);
```

2023-02-17 09:07 UTC, YDrogen commented on apps/backend/api/src/app/images/images.controller.ts
> +@Controller('images')
Guard

2023-02-17 09:08 UTC, YDrogen commented on apps/backend/api/src/app/resources-produced/resources-produced.controller.ts
> +@Controller('resources-produced')
Guard

2023-02-17 09:09 UTC, YDrogen commented on apps/backend/api/src/app/resources/dto/create-resource.dto.ts
> +  id: number;
🧐

2023-02-17 09:10 UTC, YDrogen commented on apps/backend/api/src/app/resources/resources.controller.ts
> +@Controller('resources')
Guard

2023-02-17 09:10 UTC, YDrogen commented on apps/backend/api/src/app/resources/resources.service.ts
> +      where: [{ id: id }],
```suggestion
      where: [{ id }],
```

2023-02-17 09:11 UTC, YDrogen commented on apps/backend/api/src/app/rooms/rooms.controller.ts
> +@Controller('rooms')
Guard

2023-02-17 09:12 UTC, YDrogen commented on apps/backend/api/src/app/users/dto/login-user.dto.ts
> +  username: string;
`@IsString()`

2023-02-17 09:12 UTC, YDrogen commented on apps/backend/api/src/app/users/dto/login-user.dto.ts
> +  password: string;
idem

2023-02-17 09:14 UTC, YDrogen commented on apps/backend/api/src/app/users/users.controller.ts
> +@Controller('users')
Guard

2023-02-17 09:16 UTC, YDrogen commented on apps/backend/api/src/config/migration.config.ts
> +  migrations: [__dirname + '/../migrations/*.ts'],
oui

2023-02-17 09:16 UTC, SkeidoK commented on apps/backend/api/src/app/games/games.service.ts
> +    return await this.gamesRepository.save(createGameDto);
Fait

2023-02-17 09:17 UTC, SkeidoK commented on apps/backend/api/src/app/images/images.controller.ts
> +@Controller('images')
Fait

2023-02-17 09:18 UTC, SkeidoK commented on apps/backend/api/src/app/resources-produced/resources-produced.controller.ts
> +@Controller('resources-produced')
Fait

2023-02-17 09:19 UTC, SkeidoK commented on apps/backend/api/src/app/resources-used/resources-used.controller.ts
> +@Controller('resources-used')
Fait

2023-02-17 09:19 UTC, codelande commented on apps/backend/api/src/app/forge/forge.controller.ts
> +}
je suis pas sur que commenter suffise, le fichier est inutile en prod non ?

2023-02-17 09:19 UTC, SkeidoK commented on apps/backend/api/src/app/resources/dto/create-resource.dto.ts
> +  id: number;
Fait

2023-02-17 09:20 UTC, SkeidoK commented on apps/backend/api/src/app/resources/resources.controller.ts
> +@Controller('resources')
Fait

2023-02-17 09:20 UTC, SkeidoK commented on apps/backend/api/src/app/resources/resources.service.ts
> +      where: [{ id: id }],
Fait

2023-02-17 09:21 UTC, SkeidoK commented on apps/backend/api/src/app/rooms/rooms.controller.ts
> +@Controller('rooms')
Fait

2023-02-17 09:22 UTC, SkeidoK commented on apps/backend/api/src/app/users/dto/login-user.dto.ts
> +  username: string;
Fait

2023-02-17 09:22 UTC, SkeidoK commented on apps/backend/api/src/app/users/dto/login-user.dto.ts
> +  password: string;
Fait

2023-02-17 09:23 UTC, SkeidoK commented on apps/backend/api/src/app/users/users.controller.ts
> +@Controller('users')
Fait

2023-02-17 09:25 UTC, YDrogen commented on apps/backend/api/src/entities/bonus-malus.entity.ts
> +  label: string;
Tout a une length de 255 ?

2023-02-17 09:26 UTC, YDrogen commented on apps/backend/api/src/entities/character.entity.ts
> +  image: string;
idem

2023-02-17 09:34 UTC, YDrogen commented on apps/backend/api/src/app/game-events/game-events.controller.ts
> +  @UseGuards(JwtAuthGuard)
Tu peux virer le guard ici du coup

2023-02-17 09:34 UTC, YDrogen commented on apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
> +
```suggestion
```

2023-02-17 09:37 UTC, YDrogen commented on apps/backend/api/src/entities/event.entity.ts
> +  image: string;
Length 255 partout ?

2023-02-17 10:11 UTC, SkeidoK commented on apps/backend/api/src/app/game-events/game-events.controller.ts
> +  @UseGuards(JwtAuthGuard)
Fait

2023-02-17 10:11 UTC, paul-chatelain-fernandes requested changes

2023-02-17 10:11 UTC, SkeidoK commented on apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
> +
Fait

2023-02-17 10:29 UTC, SkeidoK commented on apps/backend/api/src/entities/bonus-malus.entity.ts
> +  label: string;
Changer sur le label

2023-02-17 10:29 UTC, YDrogen commented on apps/frontend/web/src/components/ResetGameFiller.tsx
> +        {'Password :'}
```suggestion
        {'Password:'}
```

2023-02-17 10:29 UTC, SkeidoK commented on apps/backend/api/src/entities/character.entity.ts
> +  image: string;
Mis un length max de 500

2023-02-17 10:29 UTC, SkeidoK commented on apps/backend/api/src/entities/event.entity.ts
> +  image: string;
Changer la taille du label fait

2023-02-17 10:31 UTC, YDrogen commented on apps/frontend/web/src/components/UserContactFiller.tsx
> +        {'Username :'}
```suggestion
        {'Username:'}
```

2023-02-17 10:31 UTC, YDrogen commented on apps/frontend/web/src/components/UserContactFiller.tsx
> +        {'E-mail :'}
```suggestion
        {'Email:'}
```

2023-02-17 10:37 UTC, YDrogen commented on apps/frontend/web/src/components/UserPasswordFiller.tsx
> +        {'Old password :'}
```suggestion
        {'Old password:'}
```

2023-02-17 10:37 UTC, YDrogen commented on apps/frontend/web/src/components/UserPasswordFiller.tsx
> +        {'New password :'}
```suggestion
        {'New password:'}
```

2023-02-17 10:37 UTC, SkeidoK commented on .env.sample
>  PORT=3333
Valeur laissé vu plus haut avec le formateur

2023-02-17 10:37 UTC, SkeidoK commented on .env.sample
> +DATABASE_SYNCHRONIZE=TRUE
Fait

2023-02-17 10:37 UTC, SkeidoK commented on apps/frontend/web/src/pages/About.tsx
> +          align="center"
Fait

2023-02-17 10:37 UTC, SkeidoK commented on apps/frontend/web/src/pages/Home.tsx
> +        <Box w="500px" display="flex" align="center" mt="5rem" mb="5rem">
Fait

2023-02-17 10:37 UTC, SkeidoK commented on apps/backend/api/src/app/events/dto/create-event.dto.ts
> +  name: string;
Déjà changer

2023-02-17 10:37 UTC, SkeidoK commented on apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
> +    @Body() updateTotaleSizeDto: UpdateTotalSizeGameRoomDto,
Fait

2023-02-17 10:37 UTC, SkeidoK commented on apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
> +      updateTotaleSizeDto,
FAit

2023-02-17 10:37 UTC, SkeidoK commented on apps/backend/api/src/app/game-rooms/game-rooms.service.ts
> +  async updateTotaleSize(
Fait

2023-02-17 10:37 UTC, SkeidoK commented on apps/backend/api/src/app/game-rooms/game-rooms.service.ts
> +    updateTotaleSizeDto: UpdateTotalSizeGameRoomDto,
Fait

2023-02-17 10:37 UTC, SkeidoK commented on apps/backend/api/src/app/game-rooms/game-rooms.service.ts
> +    const newTotalSize = gameRoom.totalSize + updateTotaleSizeDto.totalSize;
Fait

2023-02-17 10:37 UTC, SkeidoK commented on apps/backend/api/src/app/games/games.service.ts
> +    return await this.gamesRepository.save(createGameDto);
Fait

2023-02-17 10:37 UTC, SkeidoK commented on apps/frontend/web/src/components/ResetGameFiller.tsx
> +        {'Password :'}
Fait

2023-02-17 10:39 UTC, SkeidoK reviewed
fait

2023-02-17 10:39 UTC, SkeidoK commented on apps/frontend/web/src/components/UserContactFiller.tsx
> +        {'Username :'}
Fait

2023-02-17 10:40 UTC, SkeidoK commented on apps/frontend/web/src/components/UserContactFiller.tsx
> +        {'E-mail :'}
Fait

2023-02-17 10:40 UTC, SkeidoK commented on apps/frontend/web/src/components/UserPasswordFiller.tsx
> +        {'Old password :'}
Fait

2023-02-17 10:40 UTC, SkeidoK commented on apps/frontend/web/src/components/UserPasswordFiller.tsx
> +        {'New password :'}
Fait

2023-02-17 10:41 UTC, SkeidoK commented on apps/backend/api/src/app/game-events/game-events.controller.ts
> +    return this.gameEventsService.findAll(gameId);
Fait

2023-02-17 10:46 UTC, YDrogen commented on apps/backend/api/src/entities/bonus-malus.entity.ts
> +  @Length(30)
Pas comme ça, le `@Length` sert pour la validation, pas SQL
```suggestion
  @Column('varchar', { length: 30 })
```

2023-02-17 10:46 UTC, YDrogen commented on apps/backend/api/src/entities/character.entity.ts
> +  @Length(2, 500)
idem

2023-02-17 10:46 UTC, YDrogen commented on apps/backend/api/src/entities/event.entity.ts
> +  @Length(30)
idem

2023-02-17 10:49 UTC, YDrogen commented on apps/frontend/web/src/pages/AccountSettings.tsx
> +                {'Modify'}
```suggestion
                {'Edit'}
```

2023-02-17 10:49 UTC, YDrogen commented on apps/frontend/web/src/pages/AccountSettings.tsx
> +                  {'Modify'}
```suggestion
                  {'Edit'}
```

2023-02-17 10:50 UTC, YDrogen commented on apps/frontend/web/src/pages/GameSettings.tsx
> +import { useToast } from '@chakra-ui/react';
import déjà en haut

2023-02-17 10:51 UTC, YDrogen commented on apps/frontend/web/src/pages/GameSettings.tsx
> +                {'Modify'}
```suggestion
                {'Edit'}
```
Fais une recherche sur tout le projet pour remplacer "Modify" par "Edit" au cas où j'en ai oublié

2023-02-17 10:52 UTC, YDrogen commented on apps/frontend/web/src/pages/GameSettings.tsx
> +                  <Text as="b">{'Company name :'}</Text>
```suggestion
                  <Text as="b">{'Company name:'}</Text>
```

2023-02-17 10:52 UTC, YDrogen commented on apps/frontend/web/src/pages/GameSettings.tsx
> +                  <Text as="b">{'CEO name :'}</Text>
```suggestion
                  <Text as="b">{'CEO name:'}</Text>
```

2023-02-17 10:52 UTC, YDrogen commented on apps/frontend/web/src/pages/GameSettings.tsx
> +                  <Text as="b">{'Location :'}</Text>
```suggestion
                  <Text as="b">{'Location:'}</Text>
```

2023-02-17 10:53 UTC, YDrogen commented on apps/frontend/web/src/pages/Home.tsx
> +      bgImage="url('./overview.jpg')"
Les liens vers les images vont peut-être pas fonctionner une fois déployé. À garder à l'oeil

2023-02-17 10:54 UTC, YDrogen commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +                    {'2500 / 1 500 000'}
1.5 millions de joueurs ?

2023-02-17 10:56 UTC, YDrogen commented on apps/frontend/web/src/pages/NewGame.tsx
> +              {'Name of your company :'}
```suggestion
              {'Name of your company:'}
```

2023-02-17 10:57 UTC, YDrogen commented on apps/frontend/web/src/pages/NewGame.tsx
> +              {'CEO of your company :'}
```suggestion
              {'CEO of your company:'}
```

2023-02-17 10:57 UTC, YDrogen commented on apps/frontend/web/src/pages/Overview.tsx
> +    };
??

2023-02-17 10:58 UTC, YDrogen commented on apps/frontend/web/src/pages/Page404.tsx
> +          {"Oups, this is room 404! It's nothing, it's just the trainee!"}
```suggestion
          {"Oups, this is room 404! It's nothing, it's just the intern!"}
```
?

2023-02-17 11:00 UTC, SkeidoK commented on apps/backend/api/src/entities/bonus-malus.entity.ts
> +  @Length(30)
Fait

2023-02-17 11:00 UTC, SkeidoK commented on apps/backend/api/src/entities/character.entity.ts
> +  @Length(2, 500)
Fait

2023-02-17 11:00 UTC, SkeidoK commented on apps/backend/api/src/entities/event.entity.ts
> +  @Length(30)
Fait

2023-02-17 11:00 UTC, SkeidoK commented on apps/frontend/web/src/pages/AccountSettings.tsx
> +                {'Modify'}
Fait

2023-02-17 11:00 UTC, SkeidoK commented on apps/frontend/web/src/pages/AccountSettings.tsx
> +                  {'Modify'}
Fait

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/GameSettings.tsx
> +import { useToast } from '@chakra-ui/react';
Fait

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/GameSettings.tsx
> +                {'Modify'}
Fait

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/GameSettings.tsx
> +                  <Text as="b">{'Company name :'}</Text>
Fait

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/GameSettings.tsx
> +                  <Text as="b">{'CEO name :'}</Text>
Fait

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/GameSettings.tsx
> +                  <Text as="b">{'Location :'}</Text>
Fait

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/Home.tsx
> +      bgImage="url('./overview.jpg')"
Yes

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +                    {'2500 / 1 500 000'}
Fait

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/NewGame.tsx
> +              {'Name of your company :'}
Fait

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/NewGame.tsx
> +              {'CEO of your company :'}
Fait

2023-02-17 11:01 UTC, SkeidoK commented on apps/frontend/web/src/pages/NewGame.tsx
> +              {'Location of your company :'}
Fait

2023-02-17 11:12 UTC, YDrogen requested changes
voir

2023-02-17 11:24 UTC, ngroult submitted a review, later dismissed

2023-02-17 11:24 UTC, codelande approved these changes

2023-02-17 13:34 UTC, SkeidoK commented on apps/frontend/web/src/pages/Overview.tsx
> +    };
Fait

2023-02-17 13:35 UTC, YDrogen approved these changes

2023-02-17 13:36 UTC, merged