feat: add images for the 2d and create the baase of the rooms
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #169
Opened 2023-02-19 21:48 UTC by codelande

2023-02-19 21:49 UTC, codelande commented
ce n'est pas encore fini mais si tu as des remarque sylvain n'hésite pas a commencer a me le transmettre ;)

2023-02-20 09:24 UTC, SkeidoK requested changes

2023-02-20 09:24 UTC, SkeidoK commented on apps/frontend/web/src/components/GameFrame.tsx
> +  console.log(roomOptions.color);
console.log

2023-02-20 09:24 UTC, SkeidoK commented on apps/frontend/web/src/components/MovingSprite.tsx
> +let i = 0;
?

2023-02-20 10:05 UTC, SkeidoK submitted a review, later dismissed

2023-02-20 10:33 UTC, YDrogen requested changes
Nom des images en anglais
Ca serait cool le nombre de personnages qui change en fonction du nombre possédé
Responsive cassé

2023-02-20 10:33 UTC, YDrogen commented on apps/frontend/web/src/components/BreakRoom2D.tsx
> +function BreakRoom2D(props) {
pas typé

2023-02-20 10:33 UTC, YDrogen commented on apps/frontend/web/src/components/OpenSpace2D.tsx
> +function OpenSpace2D(props) {
pas typé

2023-02-20 10:44 UTC, YDrogen commented on apps/frontend/web/src/components/Offices2D.tsx
> +function Offices2D(props) {
pas typé

2023-02-20 13:11 UTC, MGliem approved these changes

2023-02-20 14:06 UTC, SkeidoK submitted a review, later dismissed

2023-02-20 14:10 UTC, SkeidoK approved these changes

2023-02-20 14:11 UTC, SkeidoK approved these changes

2023-02-20 14:57 UTC, YDrogen requested changes
Il reste une image en français `nouvelles`
les parenthèses dans les noms de fichiers sont déconseillées (`desk(1)Png`)

2023-02-20 14:57 UTC, YDrogen commented on apps/frontend/web/src/App.tsx
> +        <Route path="/game-frame" element={<GameFrame />} />
Inutile ?

2023-02-20 15:11 UTC, codelande commented on apps/frontend/web/src/App.tsx
> +        <Route path="/game-frame" element={<GameFrame />} />
oui bien vu j'ai oublié de supprimer

2023-02-20 17:54 UTC, YDrogen commented on apps/frontend/web/src/components/BreakRoom2D.tsx
> +        <MovingSprite character="/man1.png" />
Tu peux récupérer les `const { gameCharacters } = useContext(GameContext);`
Tu déduis la quantité comme ça
```typescript
const internQuantity = gameCharacters.filter((gc) => gc.character.name === 'intern')[0].quantity || 0;
const devQuantity = gameCharacters.filter((gc) => gc.character.name === 'developer')[0].quantity || 0;
// ...
```
```suggestion
        {[...Array.from(internQuantity)].map((_, index) => (
          <MovingSprite key={index} character="/intern.png" />
         )}
         {[...Array.from(devQuantity)].map((_, index) => (
          <MovingSprite key={index} character="/developer.png" />
         )}
```
En plus chaque perso a sa propre image
Tu peux tester avec des perso + petits si y'en a beaucoup, pour voir si ça passe (et si c'est un peu rigolo)
sinon tu peux `Math.round(quantity / 10)` dans le `...Array.from()` ou autre, à tester

2023-02-20 17:57 UTC, YDrogen commented
Au sujet du responsive:
![image](https://user-images.githubusercontent.com/13053644/220173976-74d3e648-f2fd-4f29-a0f8-709da0445522.png)
En 1540x1040
Il y a trop de vide, possible de mettre le game frame en mode "background" avec les boutons qui passent par dessus, mettre une image pour remplir, déplacer les boutons, ...

2023-02-21 11:28 UTC, codelande commented on apps/frontend/web/src/components/BreakRoom2D.tsx
> +        <MovingSprite character="/man1.png" />
fait

2023-02-21 11:29 UTC, codelande commented
j'ai ajouter une image pour combler le vide

2023-02-21 13:46 UTC, SkeidoK approved these changes

2023-02-21 13:47 UTC, SkeidoK submitted a review, later dismissed

2023-02-21 15:36 UTC, SkeidoK submitted a review, later dismissed

2023-02-21 15:58 UTC, YDrogen requested changes
Il faudrait remettre l'autre image :eyes:

2023-02-21 16:04 UTC, SkeidoK submitted a review, later dismissed

2023-02-21 16:35 UTC, YDrogen commented on apps/frontend/web/src/pages/Room.tsx
> +      </Box>
```suggestion
      <Box
        boxSize="100%"
        display={{
          base: 'flex',
          sm: 'flex',
          md: 'flex',
          lg: 'flex',
          '2xl': 'none',
        }}
        bgImage="/placeholder.png"
        bgPosition="top center"
        bgSize="cover"
        w="100%"
      />

      <Box
        boxSize="100%"
        display={{
          base: 'none',
          sm: 'none',
          md: 'none',
          lg: 'none',
          '2xl': 'flex',
        }}
        bgPosition="top center"
        bgSize="cover"
      >
        <Center pl={'70px'}>
          <GameFrame />
        </Center>
      </Box>
```

2023-02-22 08:21 UTC, SkeidoK approved these changes

2023-02-22 08:38 UTC, YDrogen approved these changes

2023-02-22 08:38 UTC, merged