feat:close the last toast
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #175
Opened 2023-02-20 15:08 UTC by SkeidoK

2023-02-20 15:08 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2023-02-20 16:21 UTC, YDrogen requested changes

2023-02-20 16:21 UTC, YDrogen commented on apps/frontend/web/src/components/RoomElementCard.tsx
> +  const toastIdRef = useRef({});
```suggestion
  const toastIdRef = useRef();
```

2023-02-20 20:22 UTC, SkeidoK commented on apps/frontend/web/src/components/RoomElementCard.tsx
> +  const toastIdRef = useRef({});
Je ne trouve le bon typage

2023-02-21 08:25 UTC, ngroult approved these changes

2023-02-21 08:26 UTC, YDrogen approved these changes

2023-02-21 08:26 UTC, merged