Feature/register
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #27
Opened 2022-12-09 13:22 UTC by codelande

2022-12-09 13:37 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/register/Register.tsx
> +import React, { useState } from 'react';
Il faut que tu supprimes "React" de ton import

2022-12-09 13:37 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/register/Register.tsx
> +  const [show, setShow] = React.useState(false);
Là aussi le "React." est inutile

2022-12-09 13:41 UTC, paul-chatelain-fernandes approved these changes

2022-12-09 13:57 UTC, YDrogen requested changes

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/1670426847821-essai.ts
> +    name = 'essai1670426847821'
"essai"

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/1670426847821-essai.ts
> +import { MigrationInterface, QueryRunner } from "typeorm";
Migration hors du dossier de migrations

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/package.json
> +    "@types/passport-jwt": "^3.0.7",
Les libs de types sont dans les `devDependencies`

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/auth/auth.controller.ts
> +import { User } from 'src/users/entities/user.entity';
Chemin pas bon

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/auth/auth.module.ts
> +import { User } from 'src/users/entities/user.entity';
Chemin pas bon

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/auth/auth.module.ts
> +import { UsersModule } from 'src/users/users.module';
Chemin pas bon

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/auth/auth.module.ts
> +import { UsersService } from 'src/users/users.service';
Chemin pas bon

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/auth/auth.service.ts
> +import { UsersService } from 'src/users/users.service';
Chemin pas bon

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/auth/auth.service.ts
> +import { User } from 'src/users/entities/user.entity';
Chemin pas bon

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/auth/auth.service.ts
> +    return crypto.createHmac('sha256', password).digest('hex');
Pourquoi installer `argon2` pour utiliser `crypto` ?

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/config/database.config.ts
> +  migrations: [__dirname + '/../migrations/*.ts'],
Doublon avec le fichier de conf de migration

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/config/database.config.ts
> +  host: process.env.DATABASE_HOST,
Pas de `process.env` il y a la lib de config qui s'occupe de les charger

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/config/database.config.ts
> +import 'dotenv/config';
du coup import inutile

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/config/migration.config.ts
> +  migrations: [__dirname + '/../migrations/*.ts'],
Doublon avec l'autre fichier de conf

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/migrations/1670427620106-yo.ts
> +    name = 'yo1670427620106'
"yo"

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/users/entities/user.entity.ts
> +import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';
C'est peut-être mieux de faire un dossier unique `entities` qui regroupe toutes les entités plutôt qu'un dossier `entities` dans chaque module avec qu'une seule entité dedans à chaque fois

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/users/users.module.ts
> +import { User } from 'src/users/entities/user.entity';
Chemin pas bon

2022-12-09 13:57 UTC, YDrogen commented on apps/backend/api/src/users/users.service.ts
> +import { User } from 'src/users/entities/user.entity';
Chemin pas bon

2022-12-09 13:57 UTC, YDrogen commented on deployment/nginx.dev.conf
> +    server_name localhost;
Pourquoi ?

2022-12-09 13:57 UTC, YDrogen commented on apps/frontend/web/src/pages/register/Register.tsx
> +import {
Fichier .css inutile ?
Pourquoi mettre le component dans un dossier `register` si il ne contient que `Register.tsx` ?

2022-12-09 13:57 UTC, YDrogen commented on apps/frontend/web/src/pages/register/Register.tsx
> +    await fetch('api/auth/register', {
Il manque un `/` avant `api`

2022-12-09 13:57 UTC, YDrogen commented on apps/frontend/web/src/pages/register/Register.tsx
> +          <Text color="#797AA6" fontSize="xl">
Idem que l'autre PR pour les couleurs

2022-12-09 13:57 UTC, YDrogen commented on apps/frontend/web/src/pages/register/Register.tsx
> +          <Heading fontSize="3xl">DevManager</Heading>
C'est plus safe de placer tous les textes bruts dans des `{" "}` : `{"DevManager"}`

2022-12-09 13:57 UTC, YDrogen commented on package.json
> +    "@apps/backend-api": "^0.0.1",
Pourquoi ?

2022-12-09 13:57 UTC, YDrogen commented on package.json
> +    "@nestjs/mapped-types": "^1.2.0",
Non

2022-12-09 13:57 UTC, YDrogen commented on package.json
> +    "cors": "^2.8.5",
Non plus

2022-12-09 13:57 UTC, YDrogen commented on package.json
> +    "dotenv": "^16.0.3",
Toujours pas

2022-12-09 13:57 UTC, YDrogen commented on package.json
> +    "i": "^0.3.7",
Encore moins

2022-12-09 13:57 UTC, YDrogen commented on package.json
> +    "npm": "^9.2.0"
et vraiment pas, non

2022-12-09 13:57 UTC, YDrogen commented on tsconfig.json
> +    "experimentalDecorators": true,
Pourquoi ?

2022-12-09 13:57 UTC, YDrogen commented on apps/frontend/web/src/main.tsx
> +    <ChakraProvider>
Il manque le theme

2022-12-15 09:19 UTC, SkeidoK commented on package.json
> +    "i": "^0.3.7",
i est une lib vachement utilisé

2022-12-15 09:19 UTC, codelande commented on apps/backend/api/src/auth/auth.service.ts
> +    return crypto.createHmac('sha256', password).digest('hex');
Je suivi la doc de nest il me semble donc je peux pas trop te dire :(

2022-12-15 09:24 UTC, codelande commented on apps/backend/api/src/config/database.config.ts
> +  host: process.env.DATABASE_HOST,
pas sur de comprendre :(

2022-12-15 09:31 UTC, codelande commented on deployment/nginx.dev.conf
> +    server_name localhost;
help

2022-12-15 10:16 UTC, codelande commented on apps/frontend/web/src/pages/register/Register.tsx
> +          <Text color="#797AA6" fontSize="xl">
je ferais un fix quand j'aurais recupere le style que nolwenn a créer

2022-12-15 10:22 UTC, codelande commented on apps/frontend/web/src/main.tsx
> +    <ChakraProvider>
j'attend de recup le theme de nolwenn comme pour les couleurs

2022-12-15 13:03 UTC, SkeidoK approved these changes

2022-12-15 16:21 UTC, YDrogen submitted a review, later dismissed

2022-12-16 08:18 UTC, SkeidoK submitted a review, later dismissed

2022-12-16 08:32 UTC, ngroult approved these changes

2022-12-16 08:42 UTC, YDrogen approved these changes

2022-12-16 08:42 UTC, merged