Features/character
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #33
Opened 2022-12-15 08:55 UTC by SkeidoK

2022-12-15 08:58 UTC, ngroult submitted a review, later dismissed

2022-12-15 10:22 UTC, YDrogen requested changes

2022-12-15 10:22 UTC, YDrogen commented on .gitignore
> +deployment/back.env
```suggestion
deployment/*.env
# ou
**/*.env
```

2022-12-15 10:22 UTC, YDrogen commented on apps/backend/api/src/config/migration.config.ts
> +  ...databaseConfig,
Déplacer le `databaseConfig` ici et importer les entités

2022-12-15 10:22 UTC, YDrogen commented on apps/backend/api/src/config/database.config.ts
> +export const databaseConfig: DataSourceOptions = {
Déplacer les entities dans un fichier externe

2022-12-15 10:22 UTC, YDrogen commented on apps/backend/api/src/app.module.ts
> +    CharactersModule,
Configurer TypeOrm avec le configService
https://docs.nestjs.com/techniques/database#async-configuration

2022-12-15 11:38 UTC, codelande approved these changes

2022-12-15 13:28 UTC, YDrogen requested changes

2022-12-15 13:28 UTC, YDrogen commented on apps/backend/api/src/app.module.ts
> +        synchronize: true,
Ceci doit être une variable d'environnement qui est false par défaut

2022-12-15 13:28 UTC, YDrogen commented on apps/backend/api/src/app.module.ts
> +        username: configService.get('USERNAME'),
Ça ne fonctionne pas ça; Dans le .get il y a le nom de ce qui se trouve dans le `.env`

2022-12-15 13:28 UTC, YDrogen commented on apps/backend/api/src/config/entities.ts
> +import { Character } from 'src/characters/characters/character.entity';
Mauvais import

2022-12-15 13:28 UTC, YDrogen commented on apps/backend/api/src/config/migration.config.ts
> +
manque le import dotenv

2022-12-15 14:00 UTC, codelande approved these changes

2022-12-15 15:38 UTC, YDrogen requested changes

2022-12-15 15:38 UTC, YDrogen commented on apps/frontend/web/src/main.tsx
> +import './index.css';
Pourquoi importer un CSS vide ?

2022-12-15 15:38 UTC, YDrogen commented on .gitignore
>  deployment/*.env
Du coup cette ligne ne sert plus

2022-12-15 15:38 UTC, YDrogen commented on apps/backend/api/src/config/migration.config.ts
> +  entities: entities,
Tu peux faire ça plutôt
```suggestion
  entities,
```

2022-12-16 08:17 UTC, codelande approved these changes

2022-12-16 09:39 UTC, ngroult approved these changes

2022-12-16 09:42 UTC, YDrogen requested changes

2022-12-16 09:42 UTC, YDrogen commented on .gitignore
> +**/*.env
Doublon

2022-12-16 09:42 UTC, YDrogen commented on apps/backend/api/src/app.module.ts
> +        entities: entities,
```suggestion
        entities,
```
Si la props et la variable ont le même nom, on peut abréger comme ça

2022-12-16 09:42 UTC, YDrogen commented on apps/frontend/web/src/main.tsx
> +  </React.StrictMode>
Surtout pas, le `<React.StrictMode>` doit être le premier élément

2022-12-16 10:22 UTC, codelande approved these changes

2022-12-16 10:23 UTC, YDrogen approved these changes

2022-12-16 10:23 UTC, merged