Feature/room
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #37
Opened 2022-12-15 14:01 UTC by SkeidoK

2022-12-15 14:05 UTC, codelande requested changes

2022-12-15 14:05 UTC, codelande commented on apps/frontend/web/src/main.tsx
> +    <ChakraProvider>
il y a 2 chakra provider je pense que ca va pas

2022-12-15 14:08 UTC, codelande commented on apps/frontend/web/src/pages/register/Register.tsx
> +import {
pk le register est dans la PR ?
Tu as resolve les conflicts ?

2022-12-15 14:13 UTC, codelande approved these changes

2022-12-16 08:40 UTC, codelande approved these changes

2022-12-16 08:52 UTC, ngroult approved these changes

2022-12-16 09:45 UTC, YDrogen requested changes

2022-12-16 09:45 UTC, YDrogen commented on apps/backend/api/src/app.module.ts
> +        entities: entities,
```suggestion
        entities,
```

Quand la props et la variable qui va dedans sont identiques, on peut simplifier comme ça

2022-12-16 09:45 UTC, YDrogen commented on apps/backend/api/src/rooms/room/room.entity.ts
> +  @Column()
Il faut bien typer les colonnes (SQL)

2022-12-16 11:04 UTC, ngroult approved these changes

2022-12-16 11:31 UTC, YDrogen approved these changes

2022-12-16 11:31 UTC, merged