Feature/new game
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #40
Opened 2022-12-16 09:17 UTC by paul-chatelain-fernandes

2022-12-16 10:20 UTC, codelande requested changes

2022-12-16 10:20 UTC, codelande commented on apps/backend/api/src/games/entities/game.entity.ts
> +
peut-etre au moins rajouter des @NotEmpty

2022-12-16 10:20 UTC, codelande commented on apps/frontend/web/src/components/CompanyImageRadioCard/index.tsx
> +
pas la peine de mettre le component dans un dossier a son nom

2022-12-16 10:20 UTC, codelande commented on apps/frontend/web/src/pages/NewGame/index.tsx
> +import { useState } from 'react';
pareil que pour le component pas la peine de créer un dossier

2022-12-16 10:20 UTC, codelande commented on apps/frontend/web/src/pages/NewGame/index.tsx
> +import { useState } from 'react';
tu peux aussi delete le .css qui est vide

2022-12-16 10:40 UTC, codelande approved these changes

2022-12-16 11:04 UTC, YDrogen requested changes

2022-12-16 11:04 UTC, YDrogen commented on apps/frontend/web/src/pages/NewGame.tsx
> +      idImage: parseInt(companyImage, 10),
Pourquoi mettre des `string` si c'est pour `parseInt` après ? Pourquoi pas directement typer en `number` ?

2022-12-16 11:04 UTC, YDrogen commented on apps/frontend/web/src/pages/NewGame.tsx
> +      <Modal isOpen={isOpen} onClose={onClose} size="xl">
C'est une bonne pratique (je pense) de sortir les Modal dans des fichiers spéciaux car elles peuvent contenir beaucoup de code

2022-12-16 13:34 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/NewGame.tsx
> +      idImage: parseInt(companyImage, 10),
Parce que Segun n'accepte que du string dans les input, pas de number

2022-12-16 13:51 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/NewGame.tsx
> +          <form onSubmit={handleSubmit(onSubmit)}>
Hmm bah ça marche sans callback donc je sais pas s'il manque un callback

2022-12-16 14:07 UTC, codelande approved these changes

2022-12-16 14:12 UTC, YDrogen requested changes

2022-12-16 14:12 UTC, YDrogen commented on apps/backend/api/src/config/database.config.ts
> +import { DataSourceOptions } from 'typeorm';
Il faut le delete ce fichier oskour

2022-12-16 14:12 UTC, YDrogen commented on apps/backend/api/src/games/entities/game.entity.ts
> +  @Column('varchar')
Le typage comprend aussi les `length` et `width` pour ne pas laisser par défaut

2022-12-16 14:12 UTC, YDrogen commented on apps/frontend/web/src/pages/NewGame.tsx
> +      idImage: parseInt(companyImage, 10),
Tu parles de Monsieur Segun Adebayo ou du créateur de la librairie React Hook Forms ?

2022-12-16 14:57 UTC, codelande submitted a review, later dismissed

2022-12-16 15:57 UTC, YDrogen requested changes

2022-12-16 15:57 UTC, YDrogen commented on apps/backend/api/src/games/entities/game.entity.ts
> +  @PrimaryGeneratedColumn()
C'est ici le `unsigned`

2022-12-16 16:27 UTC, YDrogen approved these changes

2022-12-19 08:21 UTC, SkeidoK approved these changes

2022-12-19 10:32 UTC, merged