feat(frontend/web): add redirection when start the game
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #61
Opened 2022-12-21 09:03 UTC by paul-chatelain-fernandes

2022-12-21 09:18 UTC, codelande approved these changes

2022-12-21 10:14 UTC, YDrogen requested changes

2022-12-21 10:14 UTC, YDrogen commented on apps/frontend/web/src/pages/NewGame.tsx
> +        return navigate('/game/overview');
Il manque pas un `if` pour vérifier que c'est bien `success` ? Parce que là, même une erreur redirige vers `overview`

2023-01-04 15:34 UTC, SkeidoK approved these changes

2023-01-04 18:41 UTC, YDrogen approved these changes

2023-01-04 18:41 UTC, merged