Add links and navbar in each components
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #65
Opened 2023-01-04 09:05 UTC by ngroult

2023-01-04 09:09 UTC, codelande approved these changes

2023-01-04 14:39 UTC, YDrogen requested changes

2023-01-04 14:39 UTC, YDrogen commented on apps/frontend/web/src/components/Navbar.tsx
> +          </Link>
L'indent est pas bonne là :(

2023-01-05 15:50 UTC, codelande approved these changes

2023-01-05 15:57 UTC, YDrogen requested changes

2023-01-05 15:57 UTC, YDrogen commented on apps/frontend/web/src/components/NavbarRooms.tsx
> +    isOpen ? (paddingLeftIcons = '30px') : (paddingLeftIcons = '15px');
???
Pourquoi pas directement dans le `const paddingLeftIcons` ?

2023-01-06 15:57 UTC, SkeidoK approved these changes

2023-01-07 16:43 UTC, YDrogen approved these changes

2023-01-07 16:43 UTC, merged