Feature/buy first room
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #67
Opened 2023-01-04 14:53 UTC by paul-chatelain-fernandes

2023-01-04 14:59 UTC, SkeidoK approved these changes

2023-01-04 15:02 UTC, SkeidoK approved these changes

2023-01-04 18:48 UTC, YDrogen requested changes

2023-01-04 18:48 UTC, YDrogen commented on apps/backend/api/src/app/game-resources/entities/game-resource.entity.ts
> +  idGame: number;
C'est pas censé être une relation vers l'entité game ?

2023-01-04 18:48 UTC, YDrogen commented on apps/backend/api/src/app/game-resources/entities/game-resource.entity.ts
> +  idResource: number;
C'est pas censé être une relation vers l'entité resource ?

2023-01-04 18:48 UTC, YDrogen commented on apps/frontend/web/src/pages/Overview.tsx
> +  const [showGetCheck, setShowGetCheck] = useState(true);
C'est une bonne pratique de préfixer les boolean avec de l'impératif : `should` `is` `must`

2023-01-04 18:48 UTC, YDrogen commented on apps/frontend/web/src/pages/Overview.tsx
> +            <br />
Un `<br />` dans un bouton ??

2023-01-04 18:48 UTC, YDrogen commented on package.json
> +    "@nestjs/mapped-types": "*",
Nope, si ce package est requis, c'est pas ici

2023-01-06 09:12 UTC, codelande approved these changes

2023-01-07 16:44 UTC, YDrogen requested changes

2023-01-07 16:44 UTC, YDrogen commented on apps/frontend/web/src/components/Navbar.tsx
> +        h="calc(100vh)"
Pas besoin de `calc` si y'a pas de calcul 👍

2023-01-07 16:44 UTC, YDrogen commented on apps/frontend/web/src/components/NavbarRooms.tsx
>          <Center pt="calc(22vh)">
Toujours pas besoin de `calc` sans calcul

(oui, c'est déjà passé dans une autre PR, j'avais pas vu)

2023-01-07 16:44 UTC, YDrogen commented on apps/frontend/web/src/pages/Overview.tsx
> +      game: { id: 1 },
Ce dont je parlais dans l'autre commentaire, c'est mieux de faire ça côté backend
(et du coup, n'importe quel joueur a juste à changer `1000` par `99999999999` avant de cliquer et il est riche avant même d'avoir commencé ?)

2023-01-07 16:44 UTC, YDrogen commented on apps/frontend/web/src/pages/Overview.tsx
> +            <Text>{'+ $ 1,000'}</Text>
Pas d'espace après $
```suggestion
            <Text>{'+ $1,000'}</Text>
```

2023-01-09 09:30 UTC, codelande approved these changes

2023-01-09 10:26 UTC, YDrogen requested changes

2023-01-09 10:26 UTC, YDrogen commented on apps/frontend/web/src/pages/Overview.tsx
> +      quantity: 1000,
Pas besoin de `quantity` ici du coup

2023-01-09 10:26 UTC, YDrogen commented on apps/backend/api/src/app/game-resources/dto/create-game-resource.dto.ts
> +  quantity: number;
À retirer

2023-01-09 10:44 UTC, SkeidoK approved these changes

2023-01-09 10:45 UTC, YDrogen approved these changes

2023-01-09 10:45 UTC, merged