Feature/leaderboard
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #69
Opened 2023-01-05 11:00 UTC by SkeidoK

2023-01-05 16:01 UTC, codelande requested changes

2023-01-06 10:37 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +                    <Image src="/badge.png" boxSize="5" mr="2"></Image>
Et une seul balise `Image` auto-fermante

2023-01-08 18:03 UTC, codelande approved these changes

2023-01-09 08:57 UTC, YDrogen requested changes

2023-01-09 08:57 UTC, YDrogen commented on apps/backend/api/src/app/users/entities/user.entity.ts
> +import { Game } from 'src/app/games/entities/game.entity';
Import pas bon

2023-01-09 08:57 UTC, YDrogen commented on apps/frontend/web/src/main.tsx
> +      <Leaderboard />
Ce n'est pas une route

2023-01-09 08:57 UTC, YDrogen commented on apps/backend/api/src/app/games/entities/game.entity.ts
> +import { User } from 'src/app/users/entities/user.entity';
Import pas ouf

2023-01-09 08:57 UTC, YDrogen commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +import {Game} from '../../../../../apps/backend/api/src/app/games/entities/game.entity'
TMTC

2023-01-09 08:57 UTC, YDrogen commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +    fetch('api/games', { method: 'GET', signal: abortController.signal })
Il manque `/`

2023-01-09 10:07 UTC, codelande approved these changes

2023-01-09 10:30 UTC, YDrogen requested changes

2023-01-09 10:30 UTC, YDrogen commented on apps/backend/api/src/app/auth/auth.controller.ts
> +import { User } from '../../entities/user.entity';
Plus besoin de `user.entity` ici comme il y a le `index.ts`

2023-01-09 10:30 UTC, YDrogen commented on apps/backend/api/src/app/auth/auth.module.ts
> +import { User } from '../../entities/user.entity';
idem

2023-01-09 10:30 UTC, YDrogen commented on apps/backend/api/src/app/auth/auth.service.ts
> +import { User } from '../../entities/user.entity';
idem

2023-01-09 10:30 UTC, YDrogen commented on apps/backend/api/src/app/games/games.module.ts
> +import { Game } from '../../entities/game.entity';
idem

2023-01-09 10:30 UTC, YDrogen commented on apps/backend/api/src/app/games/games.service.ts
> +import { Game } from '../../entities/game.entity';
idem

2023-01-09 10:30 UTC, YDrogen commented on apps/backend/api/src/app/users/users.module.ts
> +import { User } from '../../entities/user.entity';
idem

2023-01-09 10:30 UTC, YDrogen commented on apps/backend/api/src/app/users/users.service.ts
> +import { User } from '../../entities/user.entity';
idem

2023-01-09 10:30 UTC, YDrogen commented on apps/backend/api/src/config/entities.ts
> +import { Room } from '../entities/room.entity';
idem

2023-01-09 10:30 UTC, YDrogen commented on apps/backend/api/src/config/entities.ts
>  export const entities = [Character, Game, User, Room];
Techniquement, ce fichier n'est plus utile du coup

2023-01-09 10:30 UTC, YDrogen commented on apps/frontend/web/src/main.tsx
> +import Leaderboard from './pages/Leaderboard';
Importé mais pas utilisé ?

2023-01-09 10:41 UTC, codelande requested changes

2023-01-09 10:41 UTC, codelande commented on apps/frontend/web/src/main.tsx
> -import App from './App';
tu dois garder le import de app est le mettre entre les balises browserRouter

2023-01-09 10:44 UTC, codelande approved these changes

2023-01-09 14:04 UTC, codelande submitted a review, later dismissed

2023-01-09 14:14 UTC, YDrogen commented on apps/backend/api/src/app/game-resources/game-resources.service.ts
> +import { Game } from 'src/entities';
idem

2023-01-09 14:14 UTC, YDrogen commented on apps/backend/api/src/app/resources/resources.module.ts
> +import { Resource } from '../../entities/resource.entity';
idem

2023-01-09 14:14 UTC, YDrogen commented on apps/backend/api/src/app/rooms/rooms.module.ts
> +import { Room } from 'src/entities';
idem

2023-01-09 14:14 UTC, YDrogen commented on apps/backend/api/src/app/rooms/rooms.service.ts
> +import { Room } from 'src/entities';
idem

2023-01-09 14:16 UTC, YDrogen commented on apps/frontend/web/src/pages/Leaderboard.tsx
> +          {'Mondial rank'}
"Mondial" ?

2023-01-09 15:13 UTC, codelande approved these changes

2023-01-09 15:21 UTC, YDrogen approved these changes

2023-01-09 15:27 UTC, codelande approved these changes

2023-01-09 15:30 UTC, YDrogen approved these changes

2023-01-09 15:31 UTC, merged