Feature/responsive navbar
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #83
Opened 2023-01-17 15:43 UTC by ngroult

2023-01-18 08:37 UTC, paul-chatelain-fernandes requested changes

2023-01-18 08:37 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +      <Box w={`${isNavbarOpen ? '220px' : '60px'}`}>
Est-ce que la template string est utile ici ?

2023-01-18 08:37 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +          w={`${isNavbarOpen ? '220px' : '60px'}`}
Idem que plus haut?

2023-01-18 08:37 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +          <Box bg="blue.500" w={`${isNavbarOpen ? '220px' : '60px'}`} h="80px">
Idem qu'en haut?

2023-01-18 08:37 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +          pl={`${isNavbarOpen ? '220px' : '60px'}`}
Idem que plus haut?

2023-01-18 10:49 UTC, codelande approved these changes

2023-01-18 11:24 UTC, YDrogen requested changes

2023-01-18 11:24 UTC, YDrogen commented on apps/frontend/web/src/components/DrawerNavbar.tsx
> +  const paddingBetweenIcons: string = '15px';
Les `const` qui ne bougent pas peuvent être sorties hors du component 🤓

2023-01-19 08:59 UTC, codelande approved these changes

2023-01-19 09:03 UTC, paul-chatelain-fernandes requested changes

2023-01-19 09:03 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
>    const paddingBetweenIcons: string = '15px';
Comme plus haut, je crois qu'il y a pas besoin de typer ici avec l'inférence

2023-01-19 09:03 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +                  <Image src="/resume_game.png" h={iconsSize} w={iconsSize} />
Manque le `alt`

2023-01-19 09:03 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +                  <Image src="/leaderboard.png" h={iconsSize} w={iconsSize} />
`alt`

2023-01-19 09:03 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +                  <Image src="/game_settings.png" h={iconsSize} w={iconsSize} />
`alt`

2023-01-19 09:03 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +                  />
`alt`

2023-01-19 09:03 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +                  <Image src="/about.png" h={iconsSize} w={iconsSize} />
`alt`

2023-01-19 09:03 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +                  <Image src="/logout.png" h={iconsSize} w={iconsSize} />
`alt`

2023-01-19 09:03 UTC, paul-chatelain-fernandes commented on apps/frontend/web/src/components/Navbar.tsx
> +                  <Image src="/assistance.png" h={iconsSize} w={iconsSize} />
`alt`

2023-01-19 14:26 UTC, paul-chatelain-fernandes approved these changes

2023-01-19 14:34 UTC, YDrogen approved these changes

2023-01-19 14:36 UTC, merged