Feature/resources
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #85
Opened 2023-01-18 10:29 UTC by ngroult

2023-01-18 11:05 UTC, codelande requested changes

2023-01-18 11:05 UTC, codelande commented on apps/frontend/web/src/components/ResourcesBar.tsx
> +    console.log(resources);
console log

2023-01-19 08:59 UTC, codelande submitted a review, later dismissed

2023-01-19 10:21 UTC, YDrogen requested changes

2023-01-19 14:30 UTC, SkeidoK approved these changes

2023-01-19 14:37 UTC, YDrogen approved these changes

2023-01-19 14:37 UTC, merged