feat: admin interface using refine
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #98
Opened 2023-01-25 14:04 UTC by codelande

2023-01-25 16:20 UTC, paul-chatelain-fernandes requested changes
Bravo, très beau travail corentin

2023-01-26 08:40 UTC, paul-chatelain-fernandes requested changes
Le dossier Corentin

2023-01-26 08:56 UTC, paul-chatelain-fernandes approved these changes

2023-01-26 09:06 UTC, YDrogen requested changes

2023-01-26 09:06 UTC, YDrogen commented on apps/backend/api/src/app/characters/character.module.ts
> +  exports: [CharactersService],
utile ?

2023-01-26 09:06 UTC, YDrogen commented on apps/backend/api/package.json
> +    "@nestjsx/crud-typeorm": "^5.0.0-alpha.3",
utile ?

2023-01-26 09:06 UTC, YDrogen commented on apps/frontend/admin/package.json
> +    "@types/jest": "^26.0.23",
Ca c'est dans les devDeps

2023-01-26 09:06 UTC, YDrogen commented on apps/frontend/admin/package.json
> +    "@pankod/refine-cli": "^1.2.0",
surement devDeps

2023-01-26 09:06 UTC, YDrogen commented on apps/frontend/admin/src/App.tsx
> +  const API_URL = 'http://localhost/api';
Ça marche avec juste `/api` ?

2023-01-26 09:06 UTC, YDrogen commented on apps/frontend/admin/package.json
> +    "class-validator": "^0.14.0",
utile ?

2023-01-26 09:06 UTC, YDrogen commented on apps/frontend/admin/package.json
> +    "@pankod/refine-nestjsx-crud": "^3.37.0",
utile ?

2023-01-26 09:06 UTC, YDrogen commented on apps/frontend/admin/package.json
> +    "@nestjsx/crud-typeorm": "^5.0.0-alpha.3",
utile ?

2023-01-26 16:03 UTC, codelande commented on apps/frontend/admin/src/App.tsx
> +  const API_URL = 'http://localhost/api';
ca ne fonctionne pas :(

2023-01-27 11:08 UTC, SkeidoK submitted a review, later dismissed

2023-01-30 09:25 UTC, codelande commented on apps/frontend/admin/package.json
> +    "@pankod/refine-nestjsx-crud": "^3.37.0",
bonsoir, oui

2023-01-30 09:26 UTC, codelande commented on apps/frontend/admin/package.json
> +    "@pankod/refine-cli": "^1.2.0",
@nestjsx sont delete et j'ai deplacer le cli

2023-01-31 10:45 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2023-01-31 10:49 UTC, YDrogen requested changes

2023-01-31 10:49 UTC, YDrogen commented on package.json
> +    "dev:frontend:admin": "npm run dev --workspace=apps/frontend/admin",
ce script ne marche pas

2023-02-01 08:48 UTC, paul-chatelain-fernandes approved these changes

2023-02-01 09:06 UTC, merged