Feature/login native
WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager pull request #99
Opened 2023-01-25 15:52 UTC by paul-chatelain-fernandes

2023-01-25 16:11 UTC, codelande requested changes

2023-01-25 16:11 UTC, codelande commented on apps/frontend/mobile/src/screens/LoginScreen.tsx
> +      console.error(err);
console log

2023-01-25 16:14 UTC, paul-chatelain-fernandes commented on apps/frontend/mobile/src/screens/LoginScreen.tsx
> +      console.error(err);
Tqt

2023-01-26 08:27 UTC, codelande approved these changes

2023-01-26 11:24 UTC, SkeidoK submitted a review, later dismissed

2023-01-26 11:34 UTC, YDrogen requested changes
package-lock supprimé ???

2023-01-26 11:34 UTC, YDrogen commented on apps/frontend/mobile/App.tsx
> +      <StatusBar backgroundColor="#00000000" barStyle="light-content" />
Ça fait beaucoup là non ? (de 0)

2023-01-26 11:34 UTC, YDrogen commented on apps/frontend/mobile/App.tsx
> +import RegisterScreen from './src/screens/RegisterScreen';
Ce fichier (`App.tsx`) devrait être dans `src` donc il faudra aussi adapter ces imports

2023-01-30 11:33 UTC, codelande approved these changes

2023-01-30 15:41 UTC, merged